name: Deploy to Lambda
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: zip
      uses: montudor/action-zip@v1
      with:
          args: zip -qq -r code.zip .
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-west-2
        function_name: arn:aws:lambda:us-west-2:423101001045:function:say_hello_world
        zip_file: code.zip
